# Site settings
title: Troels Liebe Bentsen
email: tlb@nversion.dk
description: >
  Blog about things i'm working at the moment
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tlbdk.github.com"
github_username:  tlbdk
twitter_username: tlbdk

theme: minima
plugins:
  - jekyll-feed

# Url settings
permalink: /:year/:month/:day/:title.html
